package com.yueyinyue.Model.dao.MusicDl;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSIC_DL_RECORD.
 */
public class MusicDlRecord {

    private Long id;
    /** Not-null value. */
    private String musicId;
    /** Not-null value. */
    private String ringListenUrl;
    /** Not-null value. */
    private String picUrl;
    /** Not-null value. */
    private String songName;
    /** Not-null value. */
    private String singer;
    /** Not-null value. */
    private String absoluteDir;
    /** Not-null value. */
    private String fullSongFileName;
    private int fullSongDlPercentage;
    /** Not-null value. */
    private String vibrateRingFileName;
    private int vibrateRingDlPercentage;

    public MusicDlRecord() {
    }

    public MusicDlRecord(Long id) {
        this.id = id;
    }

    public MusicDlRecord(Long id, String musicId, String ringListenUrl, String picUrl, String songName, String singer, String absoluteDir, String fullSongFileName, int fullSongDlPercentage, String vibrateRingFileName, int vibrateRingDlPercentage) {
        this.id = id;
        this.musicId = musicId;
        this.ringListenUrl = ringListenUrl;
        this.picUrl = picUrl;
        this.songName = songName;
        this.singer = singer;
        this.absoluteDir = absoluteDir;
        this.fullSongFileName = fullSongFileName;
        this.fullSongDlPercentage = fullSongDlPercentage;
        this.vibrateRingFileName = vibrateRingFileName;
        this.vibrateRingDlPercentage = vibrateRingDlPercentage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMusicId() {
        return musicId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMusicId(String musicId) {
        this.musicId = musicId;
    }

    /** Not-null value. */
    public String getRingListenUrl() {
        return ringListenUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRingListenUrl(String ringListenUrl) {
        this.ringListenUrl = ringListenUrl;
    }

    /** Not-null value. */
    public String getPicUrl() {
        return picUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /** Not-null value. */
    public String getSongName() {
        return songName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSongName(String songName) {
        this.songName = songName;
    }

    /** Not-null value. */
    public String getSinger() {
        return singer;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSinger(String singer) {
        this.singer = singer;
    }

    /** Not-null value. */
    public String getAbsoluteDir() {
        return absoluteDir;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAbsoluteDir(String absoluteDir) {
        this.absoluteDir = absoluteDir;
    }

    /** Not-null value. */
    public String getFullSongFileName() {
        return fullSongFileName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFullSongFileName(String fullSongFileName) {
        this.fullSongFileName = fullSongFileName;
    }

    public int getFullSongDlPercentage() {
        return fullSongDlPercentage;
    }

    public void setFullSongDlPercentage(int fullSongDlPercentage) {
        this.fullSongDlPercentage = fullSongDlPercentage;
    }

    /** Not-null value. */
    public String getVibrateRingFileName() {
        return vibrateRingFileName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVibrateRingFileName(String vibrateRingFileName) {
        this.vibrateRingFileName = vibrateRingFileName;
    }

    public int getVibrateRingDlPercentage() {
        return vibrateRingDlPercentage;
    }

    public void setVibrateRingDlPercentage(int vibrateRingDlPercentage) {
        this.vibrateRingDlPercentage = vibrateRingDlPercentage;
    }

}
