package com.yueyinyue.Model.dao.MusicDl;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class MusicDlRecordDaoSession extends AbstractDaoSession {

    private final DaoConfig musicDlRecordDaoConfig;

    private final MusicDlRecordDao musicDlRecordDao;

    public MusicDlRecordDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicDlRecordDaoConfig = daoConfigMap.get(MusicDlRecordDao.class).clone();
        musicDlRecordDaoConfig.initIdentityScope(type);

        musicDlRecordDao = new MusicDlRecordDao(musicDlRecordDaoConfig, this);

        registerDao(MusicDlRecord.class, musicDlRecordDao);
    }
    
    public void clear() {
        musicDlRecordDaoConfig.getIdentityScope().clear();
    }

    public MusicDlRecordDao getMusicDlRecordDao() {
        return musicDlRecordDao;
    }

}
